#spring:
#  datasource:
#      driverClassName: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/testing_junit_2022?useTimezone=true&serverTimezone=UTC
#      username: admin
#      password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#cors:
#  originPatterns: http://localhost:8082,http://localhost:3000,http://localhost:8080